const ERROR_CODES = {
  GENERIC_ERROR: "GENERIC_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  DATABASE_ERROR: "DATABASE_ERROR",
  USER_AUTHENTICATION_ERROR: "USER_AUTHENTICATION_ERROR",
  AUTHENTICATION_FAILED_NO_USER: "AUTHENTICATION_FAILED_NO_USER",
  AUTHENTICATION_FAILED_USER_DISABLED: "AUTHENTICATION_FAILED_USER_DISABLED",
  AUTHENTICATION_FAILED_INCORRECT_CREDENTIALS:
    "AUTHENTICATION_FAILED_INCORRECT_CREDENTIALS",
  CARD_REQUEST_NOT_FOUND: "CARD_REQUEST_NOT_FOUND",
  INVALID_CARD_STATUS: "INVALID_CARD_STATUS",
  INVALID_CARD_UPDATE_STATUS: "INVALID_CARD_UPDATE_STATUS",
  EMPLOYEE_NOT_FOUND: "EMPLOYEE_NOT_FOUND",
  EMPLOYEE_EMAIL_ALREADY_EXISTS: "EMPLOYEE_EMAIL_ALREADY_EXISTS",
  EMPLOYEE_ID_ALREADY_EXISTS: "EMPLOYEE_ID_ALREADY_EXISTS",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_CREATION_FAILED_DUPLICATE_NAME: "ROLE_CREATION_FAILED_DUPLICATE_NAME",
  ROLE_UPDATE_FAILED_DUPLICATE_NAME: "ROLE_UPDATE_FAILED_DUPLICATE_NAME",
  USER_CREATION_FAILED_EMAIL_EXISTS: "USER_CREATION_FAILED_EMAIL_EXISTS",
  USER_UPDATE_FAILED_EMAIL_EXISTS: "USER_UPDATE_FAILED_EMAIL_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  RECORD_DUPLICATION_ERROR: "RECORD_DUPLICATION_ERROR",
  UN_AUTHORIZATION: "UN_AUTHORIZATION",
  INTERNAL_ERROR:"INTERNAL_ERROR"
};

const ERROR_MESSAGES = {
  GENERIC_ERROR: "An unexpected error occurred. Please try again later.",
  INVALID_INPUT: "Invalid input. Please provide valid data.",
  DATABASE_ERROR: "Database error occurred while processing  request.",
  AUTHENTICATION_FAILED_NO_USER:
    "Authentication failed. No registered user found for the given email.",
  AUTHENTICATION_FAILED_USER_DISABLED:
    "Authentication failed. User is disabled to login. Please contact admin.",
  AUTHENTICATION_FAILED_INCORRECT_CREDENTIALS:
    "Authentication failed. Incorrect username/password.",
  CARD_REQUEST_NOT_FOUND: "Card request ID does not exist.",
  EMPLOYEE_NOT_FOUND: "Employee does not exist.",
  ROLE_NOT_FOUND: "Role does not exist.",
  INVALID_CARD_STATUS: "Card status must be either 'PRINTED' or 'DISPATCHED'.",
  INVALID_CARD_UPDATE_STATUS: "Card status must be either 'ACTIVE' or 'DISABLED'.",
  EMPLOYEE_EMAIL_ALREADY_EXISTS:
    "Employee already exists with the given email address.",
  EMPLOYEE_ID_ALREADY_EXISTS:
    "Employee already exists with the given employee ID.",
  ROLE_CREATION_FAILED_DUPLICATE_NAME:
    "Role creation failed. Role name already exists!",
  ROLE_UPDATE_FAILED_DUPLICATE_NAME:
    "Role updation failed. Role name already exists!",
  USER_CREATION_FAILED_EMAIL_EXISTS:
    "User creation failed: User already exists with the given email address.",
  USER_UPDATE_FAILED_EMAIL_EXISTS:
    "User updation failed: User already exists with the given email address.",
  USER_NOT_FOUND: "User does not exist.",
  UN_AUTHORIZATION_ERROR: "User is not authorized",
  UN_AUTHORIZATION_TOKEN: "Unauthenticated access token",
  UN_AUTHORIZATION_USER: "Unauthenticated access token is not authorized",
  INTERNAL_ERROR_MESSAGE: "Internal Server error",
  UN_AUTHORIZATION_MODULE_ACCESS: "Un authorized module access",
  UN_AUTHORIZATION_SIGNATURE: "Unauthenticated signature",

};

const ERROR_TYPES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  UN_AUTHORIZATION_ERROR: "UN_AUTHORIZATION_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  PERMISSION_ERROR: "PERMISSION_ERROR",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",
  RATE_LIMIT_ERROR: "RATE_LIMIT_ERROR",
  SERVICE_UNAVAILABLE_ERROR: "SERVICE_UNAVAILABLE_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNAUTHORIZED_ERROR: "UNAUTHORIZED_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};

module.exports = { ERROR_MESSAGES, ERROR_CODES, ERROR_TYPES };
